"""
Django settings for buildmart project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path
from django.utils.translation import gettext_noop
import os


BASE_DIR = Path(__file__).resolve().parent.parent
# 国际化=============================

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True


LANGUAGES = [
    ('zh-hans', gettext_noop('Simplified Chinese')),  # 简体中文
    ('zh-hant', gettext_noop('Traditional Chinese')), # 繁体中文（可选）
    ('ja', gettext_noop('Japanese')),                 # 日语
    ('ko', gettext_noop('Korean')),                   # 韩语
    ('en', gettext_noop('English')),                  # 英语
    ('de', gettext_noop('German')),                   # 德语
    ('fr', gettext_noop('French')),                   # 法语（可选扩展）
    ('es', gettext_noop('Spanish')),                  # 西班牙语（可选扩展）
]
LOCALE_PATHS = [
    os.path.join(BASE_DIR.parent, 'locale'),
]
print("硬编码 LOCALE_PATHS:", LOCALE_PATHS)
env_path = BASE_DIR.parent / ".env"
from dotenv import load_dotenv
load_dotenv(dotenv_path=env_path)  # 强制读取项目根目录的 .env

# 调试输出
print("=== .env 文件路径 ===")
# 数据库配置
POSTGRES_HOST = os.getenv('POSTGRES_BUILDMART_HOST') or os.getenv('DB_HOST')
# print("POSTGRES_HOST:", POSTGRES_HOST)
# print("POSTGRES_PORT:", os.getenv('POSTGRES_PORT'))



SECRET_KEY = 'django-insecure-(vmo#itel@_(bv*y5j^@*4mp=7%!*d&l4r*af-fb2jj046s!(l'
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "Apps",
    "models",
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'uivsbe_backend.middleware.TimingMiddleware',  # O-07 hot-path timing sample
]
ROOT_URLCONF = 'uivsbe_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'uivsbe_backend.wsgi.application'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'tools.authentication.TokenAuthentication',
        'tools.authentication.CustomBasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'tools.permissions.IsTokenValid',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'UNAUTHENTICATED_USER': None
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'UIVBE API',
    'DESCRIPTION': 'Unified‑Interface‑View‑Business‑Entity'
                   '一站式后端极速脚手架，统一响应、视图封装、业务层、数据实体、自带 API 文档。',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

POSTGRES_HOST = (
    os.getenv('POSTGRES_BUILDMART_HOST')
    or os.getenv('DB_HOST')
    or os.getenv('POSTGRES_HOST')
)
print("POSTGRES_HOST:", POSTGRES_HOST)

# 数据库配置 - 始终配置，确保不会因为环境变量缺失而报错
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'uivsbe'),
        'USER': os.getenv('POSTGRES_USER', 'buildmart@123'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'buildmart@123'),
        'HOST': POSTGRES_HOST or '150.109.186.194',
        'PORT': os.getenv('POSTGRES_PORT', '55431'),
    }
}

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
