networks:
  buildmart_net:
    name: buildmart_net

volumes:
  redisdata:
    driver: local

services:
  redis:
    image: redis:7-alpine
    container_name: buildmart_redis
    command: redis-server --requirepass spark@0810
    ports:
      - "6390:6379"
    volumes:
      - redisdata:/data
    networks:
      - buildmart_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "spark@0810", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buildmart_backend
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    networks:
      - buildmart_net
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Running migrations..."
        python manage.py migrate --noinput
        echo "Collecting static files..."
        python manage.py collectstatic --noinput
        echo "Starting server..."
        exec gunicorn uivsbe_backend.wsgi:application -b 0.0.0.0:8000 -w 4 --timeout 120

  nginx:
    image: nginx:1.27-alpine
    container_name: buildmart_nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - buildmart_net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./page:/usr/share/nginx/html:ro
    depends_on:
      - backend
